cat:
	gcc -c bib_arqs.c
	gcc -c cat_falsificado.c
	gcc -o cat_falsificado bib_arqs.o cat_falsificado.o

busca:
	gcc -c bib_arqs.c
	gcc -c busca_e_conta.c
	gcc -o busca_e_conta bib_arqs.o busca_e_conta.o	

clean:
	rm -f *.o cat_falsificado busca_e_conta
